version: "3.8"
services:
  mysql8:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 150919
      MYSQL_DATABASE: swin_school
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
      - swin_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: "jenkins"
    privileged: true
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
volumes:
  data-mysql:
  jenkins_home:
networks:
  swin_network: